env:
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - web-scrobbler
parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.json
  tsconfigRootDir: .
plugins: ['@typescript-eslint']
rules:
  indent: [error, 4, { SwitchCase: 1 }]
  camelcase: off
  '@typescript-eslint/camelcase': off
