name: Update files on GitHub
description: Update (i.e. commit and push) files on GitHub
author: alexesprit
inputs:
  # Required
  commit-msg:
    description: Commit message
    requried: true

  file-path:
    description: Path to file to update
    requried: true

  github-token:
    description: GitHub token
    requried: true

  # Optional
  branch:
    description: Branch name
    requried: false

  allow-removing:
    desciption: Allow to remove file
    default: false
    required: false
runs:
  using: node12
  main: dist/index.js
branding:
  icon: git-commit
  color: gray-dark
